import {
  citeIceb,
  type IcebRuleCitation,
  type ShortformLocator,
} from "./source.js";

export type ShortformRuleId = `UEB-10.9-${string}`;

export interface ShortformSource {
  readonly braille: string;
  readonly citation: IcebRuleCitation<ShortformLocator>;
  readonly id: ShortformRuleId;
  readonly print: string;
}

const shortform = (
  print: string,
  braille: string,
): ShortformSource => ({
  braille,
  citation: citeIceb("10.9 and Appendix 1"),
  id: `UEB-10.9-${print}`,
  print,
});

export const SHORTFORMS: readonly ShortformSource[] = [
  shortform("about", "⠁⠃"),
  shortform("above", "⠁⠃⠧"),
  shortform("according", "⠁⠉"),
  shortform("across", "⠁⠉⠗"),
  shortform("after", "⠁⠋"),
  shortform("afternoon", "⠁⠋⠝"),
  shortform("afterward", "⠁⠋⠺"),
  shortform("again", "⠁⠛"),
  shortform("against", "⠁⠛⠌"),
  shortform("also", "⠁⠇"),
  shortform("almost", "⠁⠇⠍"),
  shortform("already", "⠁⠇⠗"),
  shortform("altogether", "⠁⠇⠞"),
  shortform("although", "⠁⠇⠹"),
  shortform("always", "⠁⠇⠺"),
  shortform("blind", "⠃⠇"),
  shortform("braille", "⠃⠗⠇"),
  shortform("could", "⠉⠙"),
  shortform("declare", "⠙⠉⠇"),
  shortform("declaring", "⠙⠉⠇⠛"),
  shortform("deceive", "⠙⠉⠧"),
  shortform("deceiving", "⠙⠉⠧⠛"),
  shortform("either", "⠑⠊"),
  shortform("friend", "⠋⠗"),
  shortform("first", "⠋⠌"),
  shortform("good", "⠛⠙"),
  shortform("great", "⠛⠗⠞"),
  shortform("him", "⠓⠍"),
  shortform("himself", "⠓⠍⠋"),
  shortform("herself", "⠓⠻⠋"),
  shortform("immediate", "⠊⠍⠍"),
  shortform("little", "⠇⠇"),
  shortform("letter", "⠇⠗"),
  shortform("myself", "⠍⠽⠋"),
  shortform("much", "⠍⠡"),
  shortform("must", "⠍⠌"),
  shortform("necessary", "⠝⠑⠉"),
  shortform("neither", "⠝⠑⠊"),
  shortform("paid", "⠏⠙"),
  shortform("perceive", "⠏⠻⠉⠧"),
  shortform("perceiving", "⠏⠻⠉⠧⠛"),
  shortform("perhaps", "⠏⠻⠓"),
  shortform("quick", "⠟⠅"),
  shortform("receive", "⠗⠉⠧"),
  shortform("receiving", "⠗⠉⠧⠛"),
  shortform("rejoice", "⠗⠚⠉"),
  shortform("rejoicing", "⠗⠚⠉⠛"),
  shortform("said", "⠎⠙"),
  shortform("such", "⠎⠡"),
  shortform("today", "⠞⠙"),
  shortform("together", "⠞⠛⠗"),
  shortform("tomorrow", "⠞⠍"),
  shortform("tonight", "⠞⠝"),
  shortform("itself", "⠭⠋"),
  shortform("its", "⠭⠎"),
  shortform("your", "⠽⠗"),
  shortform("yourself", "⠽⠗⠋"),
  shortform("yourselves", "⠽⠗⠧⠎"),
  shortform("themselves", "⠮⠍⠧⠎"),
  shortform("children", "⠡⠝"),
  shortform("should", "⠩⠙"),
  shortform("thyself", "⠹⠽⠋"),
  shortform("ourselves", "⠳⠗⠧⠎"),
  shortform("would", "⠺⠙"),
  shortform("because", "⠆⠉"),
  shortform("before", "⠆⠋"),
  shortform("behind", "⠆⠓"),
  shortform("below", "⠆⠇"),
  shortform("beneath", "⠆⠝"),
  shortform("beside", "⠆⠎"),
  shortform("between", "⠆⠞"),
  shortform("beyond", "⠆⠽"),
  shortform("conceive", "⠒⠉⠧"),
  shortform("conceiving", "⠒⠉⠧⠛"),
  shortform("oneself", "⠐⠕⠋"),
];
