import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { pathToFileURL } from "node:url";

import type { ModeProgram } from "../src/mode-engine.js";
import type { CompiledSymbol, SymbolProgram } from "../src/symbol-program.js";

interface LoadedCompilation {
  readonly classIds: Readonly<Record<string, number>>;
  readonly modeIds: Readonly<Record<string, number>>;
  readonly modeRuleIds: readonly string[];
  readonly modes: ModeProgram;
  readonly symbolRuleIds: readonly string[];
  readonly symbols: SymbolProgram;
}

const repositoryRoot = resolve(import.meta.dirname, "..");
const compiledProgramPath = resolve(
  repositoryRoot,
  "node_modules", ".cache", "ueb-translator", "grade2-rules",
  "rules", "ueb-2024", "grade1-program.js",
);
const generatedProgramPath = resolve(repositoryRoot, "src", "generated", "grade1-program.ts");
const generatedProvenancePath = resolve(
  repositoryRoot,
  "src", "generated", "grade1-provenance.ts",
);

function isRecord(value: unknown): value is Readonly<Record<string, unknown>> {
  return typeof value === "object" && value !== null;
}

function isCompiledSymbol(value: unknown): value is CompiledSymbol {
  return isRecord(value) && typeof value["braille"] === "string" &&
    (value["kind"] === "digit" || value["kind"] === "letter" || value["kind"] === "modifier" ||
      value["kind"] === "symbol") &&
    (typeof value["numericDigit"] === "string" || value["numericDigit"] === null) &&
    typeof value["print"] === "string" &&
    (typeof value["uppercasePrint"] === "string" || value["uppercasePrint"] === null);
}

function symbolProgram(value: unknown): SymbolProgram {
  const symbols = isRecord(value) ? value["symbols"] : undefined;
  if (!Array.isArray(symbols) || !symbols.every(isCompiledSymbol)) {
    throw new Error("Compiled Grade 1 symbol program is malformed.");
  }
  return { symbols };
}

function modeProgram(value: unknown): ModeProgram {
  const modes = isRecord(value) ? value["modes"] : undefined;
  if (!Array.isArray(modes) || !modes.every((mode) =>
    Array.isArray(mode) && mode.length === 5 && Array.isArray(mode[0]) &&
    mode[0].length === 4 && mode[0].every((indicator) => typeof indicator === "string") &&
    mode.slice(1).every((operand) => typeof operand === "number" && Number.isInteger(operand))
  )) {
    throw new Error("Compiled Grade 1 mode program is malformed.");
  }
  return { modes };
}

function idObject(value: unknown, label: string): Readonly<Record<string, number>> {
  if (!(value instanceof Map)) {
    throw new Error(`Compiled Grade 1 ${label} ids are malformed.`);
  }
  const entries: (readonly [string, number])[] = [];
  for (const [key, id] of value) {
    if (typeof key !== "string" || typeof id !== "number" || !Number.isInteger(id)) {
      throw new Error(`Compiled Grade 1 ${label} ids are malformed.`);
    }
    entries.push([key, id]);
  }
  return Object.fromEntries(entries);
}

function provenanceIds(value: unknown, label: string): readonly string[] {
  if (!Array.isArray(value)) {
    throw new Error(`Compiled Grade 1 ${label} provenance is malformed.`);
  }
  return value.map((entry): string => {
    const id = isRecord(entry) ? entry["id"] : undefined;
    if (typeof id !== "string" || id.length === 0) {
      throw new Error(`Compiled Grade 1 ${label} provenance is malformed.`);
    }
    return id;
  });
}

function loadCompilation(imported: unknown): LoadedCompilation {
  if (!isRecord(imported)) {
    throw new Error("Compiled Grade 1 module is malformed.");
  }
  const modes = imported["GRADE1_MODE_COMPILATION"];
  const symbols = imported["GRADE1_SYMBOL_COMPILATION"];
  if (!isRecord(modes) || !isRecord(symbols)) {
    throw new Error("Compiled Grade 1 module lacks its compilations.");
  }
  return {
    classIds: idObject(modes["classIds"], "class"),
    modeIds: idObject(modes["modeIds"], "mode"),
    modeRuleIds: provenanceIds(modes["provenance"], "mode"),
    modes: modeProgram(modes["runtime"]),
    symbolRuleIds: provenanceIds(symbols["provenance"], "symbol"),
    symbols: symbolProgram(symbols["runtime"]),
  };
}

function generatedProgram(compilation: LoadedCompilation): string {
  return "// Generated by scripts/generate-grade1.mts. Do not edit.\n" +
    'import type { ModeProgram } from "../mode-engine.js";\n' +
    'import type { SymbolProgram } from "../symbol-program.js";\n' +
    `export const GRADE1_MODE_PROGRAM: ModeProgram = ${JSON.stringify(compilation.modes, undefined, 2)};\n` +
    `export const GRADE1_SYMBOL_PROGRAM: SymbolProgram = ${JSON.stringify(compilation.symbols, undefined, 2)};\n` +
    `export const GRADE1_MODE_IDS = ${JSON.stringify(compilation.modeIds, undefined, 2)};\n` +
    `export const GRADE1_MODE_CLASS_IDS = ${JSON.stringify(compilation.classIds, undefined, 2)};\n`;
}

function generatedProvenance(compilation: LoadedCompilation): string {
  return "// Generated by scripts/generate-grade1.mts. Do not edit.\n" +
    `export const GRADE1_MODE_RULE_IDS: readonly string[] = ${JSON.stringify(compilation.modeRuleIds, undefined, 2)};\n` +
    `export const GRADE1_SYMBOL_RULE_IDS: readonly string[] = ${JSON.stringify(compilation.symbolRuleIds, undefined, 2)};\n`;
}

async function emit(path: string, content: string, check: boolean): Promise<void> {
  if (check) {
    const current = await readFile(path, "utf8");
    if (current !== content) {
      throw new Error(`${path} is not reproducible; run npm run grade1:generate.`);
    }
    return;
  }
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, content, "utf8");
}

const imported: unknown = await import(
  `${pathToFileURL(compiledProgramPath).href}?generated=${String(Date.now())}`
);
const compilation = loadCompilation(imported);
const check = process.argv.includes("--check");
await emit(generatedProgramPath, generatedProgram(compilation), check);
await emit(generatedProvenancePath, generatedProvenance(compilation), check);
