import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { pathToFileURL } from "node:url";

type ContextualGuardOpcode =
  | 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8
  | 9 | 10 | 11 | 12 | 13 | 14 | 15 | 16;
type ContextualPrecedence = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9;
type LoadedGuard = readonly [opcode: ContextualGuardOpcode, operandIndex: number];
type LoadedRule = readonly [
  input: string,
  braille: string,
  precedence: ContextualPrecedence,
  guardOffset: number,
  guardCount: number,
];

interface LoadedProgram {
  readonly guards: readonly LoadedGuard[];
  readonly rules: readonly LoadedRule[];
  readonly stringOperands: readonly string[];
}

interface LoadedCompilation {
  readonly ids: readonly string[];
  readonly runtime: LoadedProgram;
}

const repositoryRoot = resolve(import.meta.dirname, "..");
const compiledProgramPath = resolve(
  repositoryRoot,
  "node_modules",
  ".cache",
  "ueb-translator",
  "grade2-rules",
  "program.js",
);
const generatedProgramPath = resolve(
  repositoryRoot,
  "src",
  "generated",
  "grade2-program.ts",
);
const generatedProvenancePath = resolve(
  repositoryRoot,
  "src",
  "generated",
  "grade2-provenance.ts",
);

function isRecord(value: unknown): value is Readonly<Record<string, unknown>> {
  return typeof value === "object" && value !== null;
}

function isIntegerInRange(value: unknown, minimum: number, maximum: number): value is number {
  return Number.isInteger(value) && typeof value === "number" &&
    value >= minimum && value <= maximum;
}

function isContextualGuardOpcode(value: unknown): value is ContextualGuardOpcode {
  return isIntegerInRange(value, 0, 16);
}

function isContextualPrecedence(value: unknown): value is ContextualPrecedence {
  return isIntegerInRange(value, 0, 9);
}

function loadCompilation(module: unknown): LoadedCompilation {
  const candidate = isRecord(module)
    ? module["GRADE2_CONTEXTUAL_COMPILATION"]
    : undefined;
  if (!isRecord(candidate) || !isRecord(candidate["runtime"])) {
    throw new Error("Compiled Grade 2 module has no contextual compilation.");
  }
  const runtime = candidate["runtime"];
  const rawRules = runtime["rules"];
  const rawGuards = runtime["guards"];
  const rawOperands = runtime["stringOperands"];
  const rawProvenance = candidate["provenance"];
  if (
    !Array.isArray(rawRules) || !Array.isArray(rawGuards) ||
    !Array.isArray(rawOperands) || !Array.isArray(rawProvenance) ||
    !rawOperands.every((operand) => typeof operand === "string")
  ) {
    throw new Error("Compiled Grade 2 contextual program is malformed.");
  }

  const operands = rawOperands.map((operand): string => {
    if (typeof operand !== "string") {
      throw new Error("Compiled Grade 2 contextual program has a malformed operand.");
    }
    return operand;
  });
  const guards: LoadedGuard[] = rawGuards.map((guard): LoadedGuard => {
    if (
      !Array.isArray(guard) || guard.length !== 2 ||
      !isContextualGuardOpcode(guard[0]) ||
      !isIntegerInRange(guard[1], 0, operands.length - 1)
    ) {
      throw new Error("Compiled Grade 2 contextual program has a malformed guard.");
    }
    return [guard[0], guard[1]];
  });
  const rules: LoadedRule[] = rawRules.map((rule): LoadedRule => {
    if (
      !Array.isArray(rule) || rule.length !== 5 ||
      typeof rule[0] !== "string" || rule[0].length === 0 ||
      typeof rule[1] !== "string" || rule[1].length === 0 ||
      !isContextualPrecedence(rule[2]) ||
      !isIntegerInRange(rule[3], 0, guards.length) ||
      !isIntegerInRange(rule[4], 0, guards.length - rule[3])
    ) {
      throw new Error("Compiled Grade 2 contextual program has a malformed rule.");
    }
    return [rule[0], rule[1], rule[2], rule[3], rule[4]];
  });
  const ids = rawProvenance.map((source): string => {
    const id = isRecord(source) ? source["id"] : undefined;
    if (typeof id !== "string" || id.length === 0) {
      throw new Error("Compiled Grade 2 contextual provenance is malformed.");
    }
    return id;
  });
  if (ids.length !== rules.length) {
    throw new Error("Compiled Grade 2 runtime and provenance are misaligned.");
  }
  return {
    ids,
    runtime: { guards, rules, stringOperands: operands },
  };
}

function generatedProgram(program: LoadedProgram): string {
  return `// Generated by scripts/generate-grade2.mts. Do not edit.\n` +
    `export type ContextualGuardOpcode = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 | 16;\n` +
    `export type ContextualPrecedence = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9;\n` +
    `export type ContextualGuardTuple = readonly [opcode: ContextualGuardOpcode, operandIndex: number];\n` +
    `export type ContextualRuleTuple = readonly [input: string, braille: string, precedence: ContextualPrecedence, guardOffset: number, guardCount: number];\n` +
    `export interface Grade2RuntimeProgram { readonly guards: readonly ContextualGuardTuple[]; readonly rules: readonly ContextualRuleTuple[]; readonly stringOperands: readonly string[]; }\n` +
    `export const GRADE2_PROGRAM: Grade2RuntimeProgram = ${JSON.stringify(program, undefined, 2)};\n`;
}

function generatedProvenance(ids: readonly string[]): string {
  return `// Generated by scripts/generate-grade2.mts. Do not edit.\n` +
    'export type Grade2RuleId = `UEB-10.${1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9}-${string}` | `UEB-Appendix-1-${string}-${string}`;\n' +
    `export const GRADE2_RULE_IDS: readonly Grade2RuleId[] = ${JSON.stringify(ids, undefined, 2)};\n`;
}

async function emit(path: string, content: string, check: boolean): Promise<void> {
  if (check) {
    const current = await readFile(path, "utf8");
    if (current !== content) {
      throw new Error(`${path} is not reproducible; run npm run grade2:generate.`);
    }
    return;
  }
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, content, "utf8");
}

const imported: unknown = await import(
  `${pathToFileURL(compiledProgramPath).href}?generated=${String(Date.now())}`
);
const compilation = loadCompilation(imported);
const check = process.argv.includes("--check");
await emit(generatedProgramPath, generatedProgram(compilation.runtime), check);
await emit(generatedProvenancePath, generatedProvenance(compilation.ids), check);
