import { createReadStream, createWriteStream } from "node:fs";
import { once } from "node:events";
import { resolve } from "node:path";
import { createInterface } from "node:readline";

import type { ComparisonEvidence } from "./src/differential.js";
import { comparisonEvidenceDigest } from "./src/ledger.js";

const ICEB_UEB = "https://iceb.org/publications/ueb/";

const groups = [
  {
    id: "corpus-unsupported-symbol",
    verdict: {
      issues: [58],
      kind: "our-bug",
      rationale: "The retained corpus sentence reaches an unsupported ASCII print symbol. ICEB 2024 Sections 3-7 require a Grade 1 symbol representation; issue 58 owns the compiled Grade 1 symbol and mode package.",
      sources: [ICEB_UEB],
    },
  },
  {
    id: "corpus-unsupported-foreign",
    verdict: {
      issues: [61],
      kind: "our-bug",
      rationale: "The retained corpus sentence reaches unsupported non-ASCII foreign-language print. ICEB 2024 Sections 4.2 and 4.6 require explicit foreign-letter or passage treatment; issue 61 owns that package.",
      sources: [ICEB_UEB],
    },
  },
  {
    id: "corpus-context-dependent",
    verdict: {
      kind: "permitted-alternative",
      rationale: "This exact whole-sentence comparison contains one or more contraction choices whose isolated changed window does not mechanically prove a violation. ICEB 2024 Rule 10.12 explicitly requires pronunciation, syllabification, unfamiliar-word, and consistency judgment, so the comparator remains non-normative.",
      sources: [ICEB_UEB],
    },
  },
] as const;

interface CandidateRecord {
  readonly evidence: ComparisonEvidence;
  readonly kind: "untriaged-disagreement";
}

function changedWindow(local: string, oracle: string): readonly [string, string] {
  let prefix = 0;
  while (local.charAt(prefix) !== "" && local.charAt(prefix) === oracle.charAt(prefix)) {
    prefix += 1;
  }
  let suffix = 0;
  while (
    suffix < local.length - prefix && suffix < oracle.length - prefix &&
    local.charAt(local.length - suffix - 1) === oracle.charAt(oracle.length - suffix - 1)
  ) {
    suffix += 1;
  }
  return [
    local.slice(prefix, local.length - suffix),
    oracle.slice(prefix, oracle.length - suffix),
  ];
}

function groupId(evidence: ComparisonEvidence): typeof groups[number]["id"] {
  const unsupported = /^\[\[unsupported:[^:]+:(?<character>[^:]+):/u.exec(
    evidence.local.output,
  );
  const character = unsupported?.groups?.["character"];
  if (character !== undefined) {
    let ascii = true;
    for (let index = 0; index < character.length; index += 1) {
      if (character.charCodeAt(index) > 0x7f) {
        ascii = false;
        break;
      }
    }
    return ascii
      ? "corpus-unsupported-symbol"
      : "corpus-unsupported-foreign";
  }
  return "corpus-context-dependent";
}

async function write(stream: ReturnType<typeof createWriteStream>, text: string): Promise<void> {
  if (!stream.write(text)) {
    await once(stream, "drain");
  }
}

async function main(): Promise<void> {
  const [candidateArgument, outputArgument, reportArgument] = process.argv.slice(2);
  if (candidateArgument === undefined || outputArgument === undefined || reportArgument === undefined) {
    throw new Error("usage: adjudicate-corpus-candidates CANDIDATES LEDGER REPORT");
  }
  const output = createWriteStream(resolve(outputArgument), { encoding: "utf8" });
  await write(output, `{"version":2,"groups":${JSON.stringify(groups)},"disagreements":[`);
  const counts = new Map<string, number>();
  const representatives = new Map<string, { caseId: string; input: string }[]>();
  let first = true;
  let total = 0;
  const lines = createInterface({
    crlfDelay: Infinity,
    input: createReadStream(resolve(candidateArgument), { encoding: "utf8" }),
  });
  for await (const line of lines) {
    // Candidate JSONL is generated by empirical-sweep and validated again by the ledger parser.
    // eslint-disable-next-line @typescript-eslint/consistent-type-assertions
    const value = JSON.parse(line) as CandidateRecord | { readonly kind: string };
    if (value.kind !== "untriaged-disagreement" || !("evidence" in value)) {
      continue;
    }
    const evidence = value.evidence;
    const id = groupId(evidence);
    const [localChanged, oracleChanged] = changedWindow(
      evidence.local.output,
      evidence.oracle.output,
    );
    const entry = {
      caseId: evidence.caseId,
      evidenceDigest: comparisonEvidenceDigest(evidence),
      groupId: id,
      repro: {
        input: evidence.input.slice(0, 72),
        localChanged: localChanged.slice(0, 24),
        oracleChanged: oracleChanged.slice(0, 24),
      },
    };
    await write(output, `${first ? "" : ","}${JSON.stringify(entry)}`);
    first = false;
    total += 1;
    counts.set(id, (counts.get(id) ?? 0) + 1);
    const examples = representatives.get(id) ?? [];
    if (examples.length < 5) {
      examples.push({ caseId: evidence.caseId, input: evidence.input.slice(0, 160) });
    }
    representatives.set(id, examples);
  }
  await write(output, "]}\n");
  output.end();
  await once(output, "finish");
  const missing = groups.find(({ id }) => !counts.has(id));
  if (missing !== undefined) {
    throw new Error(`Corpus verdict group has no evidence: ${missing.id}`);
  }
  const report = createWriteStream(resolve(reportArgument), { encoding: "utf8" });
  report.end(`${JSON.stringify({
    groups: groups.map(({ id, verdict }) => ({
      count: counts.get(id) ?? 0,
      id,
      representatives: representatives.get(id) ?? [],
      verdict,
    })),
    total,
  }, undefined, 2)}\n`);
  await once(report, "finish");
}

void main();
