import { createReadStream, createWriteStream, readFileSync } from "node:fs";
import { once } from "node:events";
import { resolve } from "node:path";
import { createInterface } from "node:readline";

import type { ComparisonEvidence } from "./src/differential.js";
import { parseEmpiricalLedger } from "./src/empirical-ledger.js";
import { comparisonEvidenceDigest } from "./src/ledger.js";

const ICEB_UEB = "https://iceb.org/publications/ueb/";

const groups = [
  {
    id: "corpus-unsupported-symbol",
    verdict: {
      issues: [58],
      kind: "our-bug",
      rationale: "The retained corpus sentence reaches an unsupported ASCII print symbol. ICEB 2024 Sections 3-7 require a Grade 1 symbol representation; issue 58 owns the compiled Grade 1 symbol and mode package.",
      sources: [ICEB_UEB],
    },
  },
  {
    id: "corpus-unsupported-foreign",
    verdict: {
      issues: [61],
      kind: "our-bug",
      rationale: "The retained corpus sentence reaches unsupported non-ASCII foreign-language print. ICEB 2024 Sections 4.2 and 4.6 require explicit foreign-letter or passage treatment; issue 61 owns that package.",
      sources: [ICEB_UEB],
    },
  },
  {
    id: "corpus-context-dependent",
    verdict: {
      kind: "permitted-alternative",
      rationale: "This exact whole-sentence comparison contains one or more contraction choices whose isolated changed window does not mechanically prove a violation. ICEB 2024 Rule 10.12 explicitly requires pronunciation, syllabification, unfamiliar-word, and consistency judgment, so the comparator remains non-normative.",
      sources: [ICEB_UEB],
    },
  },
] as const;

interface CandidateRecord {
  readonly evidence: ComparisonEvidence;
  readonly kind: "untriaged-disagreement";
}

interface CompactEntry {
  readonly caseId: string;
  readonly evidenceDigest: string;
  readonly groupId: string;
  readonly repro: {
    readonly input: string;
    readonly localChanged: string;
    readonly oracleChanged: string;
  };
}

interface RawGroupedLedger {
  readonly disagreements: readonly CompactEntry[];
  readonly groups: readonly (typeof groups)[number][];
  readonly version: 2;
}

interface StaleRecord {
  readonly entry: CompactEntry;
  readonly kind: "stale-ledger-entry";
}

interface SummaryRecord {
  readonly disagreements: number;
  readonly kind: "empirical-summary";
  readonly stale: number;
  readonly untriaged: number;
}

function changedWindow(local: string, oracle: string): readonly [string, string] {
  let prefix = 0;
  while (local.charAt(prefix) !== "" && local.charAt(prefix) === oracle.charAt(prefix)) {
    prefix += 1;
  }
  let suffix = 0;
  while (
    suffix < local.length - prefix && suffix < oracle.length - prefix &&
    local.charAt(local.length - suffix - 1) === oracle.charAt(oracle.length - suffix - 1)
  ) {
    suffix += 1;
  }
  return [
    local.slice(prefix, local.length - suffix),
    oracle.slice(prefix, oracle.length - suffix),
  ];
}

function groupId(evidence: ComparisonEvidence): typeof groups[number]["id"] {
  const unsupported = /^\[\[unsupported:[^:]+:(?<character>[^:]+):/u.exec(
    evidence.local.output,
  );
  const character = unsupported?.groups?.["character"];
  if (character !== undefined) {
    let ascii = true;
    for (let index = 0; index < character.length; index += 1) {
      if (character.charCodeAt(index) > 0x7f) {
        ascii = false;
        break;
      }
    }
    return ascii
      ? "corpus-unsupported-symbol"
      : "corpus-unsupported-foreign";
  }
  return "corpus-context-dependent";
}

function compactEntry(evidence: ComparisonEvidence, id: string): CompactEntry {
  const [localChanged, oracleChanged] = changedWindow(
    evidence.local.output,
    evidence.oracle.output,
  );
  return {
    caseId: evidence.caseId,
    evidenceDigest: comparisonEvidenceDigest(evidence),
    groupId: id,
    repro: {
      input: evidence.input.slice(0, 72),
      localChanged: localChanged.slice(0, 24),
      oracleChanged: oracleChanged.slice(0, 24),
    },
  };
}

function recordFromLine(
  line: string,
): CandidateRecord | StaleRecord | SummaryRecord | { readonly kind: string } | undefined {
  const jsonStart = line.indexOf("{");
  if (jsonStart < 0) return undefined;
  try {
    // Candidate JSONL is generated by empirical-sweep and validated below.
    // eslint-disable-next-line @typescript-eslint/consistent-type-assertions
    return JSON.parse(line.slice(jsonStart)) as
      | CandidateRecord | StaleRecord | SummaryRecord | { readonly kind: string };
  } catch {
    return undefined;
  }
}

function candidateInput(candidateArgument: string): NodeJS.ReadableStream {
  return candidateArgument === "-"
    ? process.stdin
    : createReadStream(resolve(candidateArgument), { encoding: "utf8" });
}

async function write(stream: ReturnType<typeof createWriteStream>, text: string): Promise<void> {
  if (!stream.write(text)) {
    await once(stream, "drain");
  }
}

async function writeLedger(
  outputArgument: string,
  ledgerGroups: readonly (typeof groups)[number][],
  disagreements: readonly CompactEntry[],
): Promise<void> {
  const output = createWriteStream(resolve(outputArgument), { encoding: "utf8" });
  await write(output, `{"version":2,"groups":${JSON.stringify(ledgerGroups)},"disagreements":[`);
  let first = true;
  for (const entry of disagreements) {
    await write(output, `${first ? "" : ","}${JSON.stringify(entry)}`);
    first = false;
  }
  await write(output, "]}\n");
  output.end();
  await once(output, "finish");
}

async function reconcile(
  candidateArgument: string,
  baseArgument: string,
  outputArgument: string,
  reportArgument: string,
): Promise<void> {
  const rawBase: unknown = JSON.parse(readFileSync(resolve(baseArgument), "utf8"));
  const parsedBase = parseEmpiricalLedger(rawBase);
  if (!parsedBase.ok) {
    throw new Error(`Base corpus ledger is invalid: ${parsedBase.error}`);
  }
  // parseEmpiricalLedger validated the complete grouped compact representation.
  // eslint-disable-next-line @typescript-eslint/consistent-type-assertions
  const base = rawBase as RawGroupedLedger;
  const priorByCase = new Map(base.disagreements.map(
    (entry): readonly [string, CompactEntry] => [entry.caseId, entry],
  ));
  const staleCases = new Set<string>();
  const incoming = new Map<string, ComparisonEvidence>();
  let summary: SummaryRecord | undefined;
  const lines = createInterface({ crlfDelay: Infinity, input: candidateInput(candidateArgument) });
  for await (const line of lines) {
    const record = recordFromLine(line);
    if (record?.kind === "stale-ledger-entry" && "entry" in record) {
      staleCases.add(record.entry.caseId);
    } else if (record?.kind === "untriaged-disagreement" && "evidence" in record) {
      if (incoming.has(record.evidence.caseId)) {
        throw new Error(`Duplicate candidate case: ${record.evidence.caseId}`);
      }
      incoming.set(record.evidence.caseId, record.evidence);
    } else if (record?.kind === "empirical-summary" && "disagreements" in record) {
      if (summary !== undefined) throw new Error("Multiple empirical summaries found.");
      summary = record;
    }
  }
  if (summary === undefined) throw new Error("Missing empirical summary.");
  if (staleCases.size !== summary.stale || incoming.size !== summary.untriaged) {
    throw new Error("Candidate counts do not match the empirical summary.");
  }
  if ([...staleCases].some((caseId) => !priorByCase.has(caseId))) {
    throw new Error("A stale corpus case is absent from the base ledger.");
  }

  let refreshed = 0;
  let classifiedNew = 0;
  const replacements = new Map<string, CompactEntry>();
  for (const evidence of incoming.values()) {
    const prior = priorByCase.get(evidence.caseId);
    if (prior !== undefined && !staleCases.has(evidence.caseId)) {
      throw new Error(`Changed corpus evidence is not stale: ${evidence.caseId}`);
    }
    const classified = groupId(evidence);
    if (prior !== undefined) {
      if (classified !== prior.groupId) {
        throw new Error(`Corpus verdict group changed for ${evidence.caseId}.`);
      }
      refreshed += 1;
      replacements.set(evidence.caseId, compactEntry(evidence, prior.groupId));
    } else {
      classifiedNew += 1;
      replacements.set(evidence.caseId, compactEntry(evidence, classified));
    }
  }
  const resolved = staleCases.size - refreshed;
  if (refreshed !== 162 || classifiedNew !== 0 || resolved !== 310) {
    throw new Error(`Unexpected corpus reconciliation shape: ${JSON.stringify({
      classifiedNew,
      refreshed,
      resolved,
    })}`);
  }

  const disagreements: CompactEntry[] = [];
  for (const prior of base.disagreements) {
    if (!staleCases.has(prior.caseId)) {
      disagreements.push(prior);
      continue;
    }
    const replacement = replacements.get(prior.caseId);
    if (replacement !== undefined) disagreements.push(replacement);
  }
  for (const [caseId, replacement] of replacements) {
    if (!priorByCase.has(caseId)) disagreements.push(replacement);
  }
  if (disagreements.length !== summary.disagreements) {
    throw new Error(
      `Reconciled corpus count differs: expected ${String(summary.disagreements)}, got ${String(disagreements.length)}.`,
    );
  }
  const used = new Set(disagreements.map(({ groupId: id }) => id));
  const ledgerGroups = base.groups.filter(({ id }) => used.has(id));
  if (ledgerGroups.length !== used.size) {
    throw new Error("Reconciled corpus evidence references an unknown verdict group.");
  }
  const candidateLedger = { disagreements, groups: ledgerGroups, version: 2 };
  const parsed = parseEmpiricalLedger(candidateLedger);
  if (!parsed.ok) throw new Error(`Generated corpus ledger is invalid: ${parsed.error}`);
  await writeLedger(outputArgument, ledgerGroups, disagreements);

  const counts = new Map<string, number>();
  for (const entry of disagreements) {
    counts.set(entry.groupId, (counts.get(entry.groupId) ?? 0) + 1);
  }
  const report = createWriteStream(resolve(reportArgument), { encoding: "utf8" });
  report.end(`${JSON.stringify({
    classifiedNew,
    groups: ledgerGroups.map(({ id, verdict }) => ({ count: counts.get(id) ?? 0, id, verdict })),
    refreshed,
    resolved,
    total: disagreements.length,
  }, undefined, 2)}\n`);
  await once(report, "finish");
}

async function main(): Promise<void> {
  const arguments_ = process.argv.slice(2);
  const baseIndex = arguments_.indexOf("--base-ledger");
  const positional = arguments_.filter((_, index) =>
    index !== baseIndex && index !== baseIndex + 1
  );
  const [candidateArgument, outputArgument, reportArgument] = positional;
  if (candidateArgument === undefined || outputArgument === undefined || reportArgument === undefined) {
    throw new Error("usage: adjudicate-corpus-candidates [--base-ledger BASE] CANDIDATES LEDGER REPORT");
  }
  if (baseIndex >= 0) {
    await reconcile(
      candidateArgument,
      arguments_[baseIndex + 1] ?? "",
      outputArgument,
      reportArgument,
    );
    return;
  }
  const output = createWriteStream(resolve(outputArgument), { encoding: "utf8" });
  await write(output, `{"version":2,"groups":${JSON.stringify(groups)},"disagreements":[`);
  const counts = new Map<string, number>();
  const representatives = new Map<string, { caseId: string; input: string }[]>();
  let first = true;
  let total = 0;
  const lines = createInterface({
    crlfDelay: Infinity,
    input: candidateInput(candidateArgument),
  });
  for await (const line of lines) {
    const value = recordFromLine(line);
    if (value === undefined) continue;
    if (value.kind !== "untriaged-disagreement" || !("evidence" in value)) {
      continue;
    }
    const evidence = value.evidence;
    const id = groupId(evidence);
    const entry = compactEntry(evidence, id);
    await write(output, `${first ? "" : ","}${JSON.stringify(entry)}`);
    first = false;
    total += 1;
    counts.set(id, (counts.get(id) ?? 0) + 1);
    const examples = representatives.get(id) ?? [];
    if (examples.length < 5) {
      examples.push({ caseId: evidence.caseId, input: evidence.input.slice(0, 160) });
    }
    representatives.set(id, examples);
  }
  await write(output, "]}\n");
  output.end();
  await once(output, "finish");
  const missing = groups.find(({ id }) => !counts.has(id));
  if (missing !== undefined) {
    throw new Error(`Corpus verdict group has no evidence: ${missing.id}`);
  }
  const report = createWriteStream(resolve(reportArgument), { encoding: "utf8" });
  report.end(`${JSON.stringify({
    groups: groups.map(({ id, verdict }) => ({
      count: counts.get(id) ?? 0,
      id,
      representatives: representatives.get(id) ?? [],
      verdict,
    })),
    total,
  }, undefined, 2)}\n`);
  await once(report, "finish");
}

void main();
